# Origin Repository:  loopyd/ecs-saber
#
# Copyright: (C) 2022 by Robert Smith <nightwintertooth@gmail.com>
# Licensed under:  DBAD License -> https://dbad-license.org/
# 
# I made efforts to make this modular so you could reuse it (and so can I)
#
# The way I have structured it is by using branches to keep docsfx and
# gh-pages isolated on they own branches so your master/main repo is very
# neat and orderly.  gh-pages is completely wiped, there is no need to
# manage it anymore thanks to docsfx static content generator.
#
# As this thing's an effective drop in replacement for Jekyll for
# github pages, toss me some spare dev cash if you like it:
#
#   https://www.paypal.com/paypalme/snowflowerwolf
#
# Or choose not to donate, just "Don't Be A Dick" - The Buddah.

name: Saber7ooth's DocFX Library Deploy workflow

on:
  workflow_call:
    inputs:
      deploy_docs:
        required: true
        type: boolean
      library_name:
        required: true
        type: string
      src_branch:
        required: true
        type: string
      gh_pages_branch:
        type: string
        required: false
      github_username:
        type: string
        required: true
      github_email:
        type: string
        required: true
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Clone ${{ inputs.src_branch }} branch
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.src_branch }}
        if: ${{ inputs.deploy_docs == false }}

      - name: Clone ${{ inputs.gh_pages_branch }}
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.gh_pages_branch }}
        if: ${{ inputs.deploy_docs == true }}
      
      - name: Sanitize ${{ inputs.gh_pages.branch }} branch
        run: |
          shopt -s extglob
          git checkout ${{ inputs.gh_pages_branch }}
          git clean -dxf
          rm -rfv !(.*)
          [ ! -f "./.nojekyll" ] && touch ./.nojekyll
        shell: bash
        if: ${{ inputs.deploy_docs == true }}

      - name: Fetch build artifacts from build workflow for docs
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.library_name }}-docs
          path: docs
        if: ${{ inputs.deploy_docs == true }}

      - name: Deploy docs to github gh-pages branch.
        run: |
          mv -rfv ./docs/* ./
          rm -rfv ./docs
          git config --global user.email='${{ inptus.github_email }}'
          git config --global user.username='${{ inputs.github_username }}'
          git add .
          git commit -m 'Generated by deploy workflow.'
          git push
        shell: bash
        if: ${{ inputs.deploy_docs == true }}
