name: Release Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_lib:
    name: Build Library
    uses: loopyd/ecs-saber/.github/workflows/build.yml@master
    with:
      build_docs: false
      build_configuration: release
      library_name: LeoEcsSaber
      library_sdk_version: 3.1.x
      src_branch: master
      repo_org: loopyd
      repo_project: ecs-saber