name: DocsFx Rebuild pipeline

on:
  push:
    branches:
      - "docfx"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_lib:
    name: Build Documentation
    uses: loopyd/ecs-saber/.github/workflows/build.yml@master
    with:
      build_docs: true
      build_configuration: debug
      library_name: LeoEcsSaber
      src_branch: master
      docsfx_branch: docsfx
      repo_org: loopyd
      repo_project: ecs-saber