name: Master Build Pipeline

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_lib:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Build Library
        uses: ./.github/workflows/build.yml@master
        with:
          build_docs: false
          configuration: release
          library_name: LeoEcsSaber
          library_sdk_version: 3.1.x
          src_branch: master
          repo_org: loopyd
          repo_project: ecs-saber
        
      - name: Build Documentation
        uses: ./.github/workflows/build.yml
        with:
          build_docs: true
          configuration: debug
          library_name: LeoEcsSaber
          src_branch: master
          docsfx_branch: docsfx
          repo_org: loopyd
          repo_project: ecs-saber