name: Push pipeline

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  on_build:
    uses: ./.github/workflows/buildlib.yml
    with:
      build_docs: true
      configuration: debug
      library_name: LeoEcsSaber